### ISSUE TITLE
Deploy and test a local testnet on aws 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/infrastructure#28]
For our upcoming testnet the goal is to create a pre-testnet and make sure it all plays nice.

requirements:

- [x] #34 
- [x] #33 
- [x] #32 
- [x] #31 
- [x] #30 
- [x] #29 
- [x] #35

**Comment by yishay-dym** [comment]
Lessgo team. 

![Screen Shot 2023-01-25 at 18 53 52](https://user-images.githubusercontent.com/109034310/214627595-47406cbd-9169-488f-9eb6-ee2d2077dd20.png)

**Comment by shaolin-flow** [comment]
Closing as completed
